export const ROUTES = {
  SPLASH: '/splash',
  WELCOME: '/welcome',
  LOGIN: '/login',
  SIGNUP: '/signup',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot-password',
  HOME: '/',
  PROFILE: '/profile',
  SEARCH: '/search',
  MESSAGES: '/messages',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  SELECT_SPORTS: '/select-sports',
  CREATE_SPORTS_PROFILE: '/create-sports-profile',
  PROFILE_PICTURE_UPLOAD: '/profile-picture-upload',
  PERSONAL_INFORMATION: '/personal-information',
  PLAYING_INFORMATION: '/playing-information',
  PROFILE_COMPLETION: '/profile-completion',
  OWN_PROFILE: '/profile/me',
} as const;
